In [1]:
import gmaps
import numpy as np
import pandas as pd
import requests
import time
import json
from scipy.stats import linregress
from matplotlib import pyplot as plt
from api_keys import g_key

In [2]:
data_df = pd.read_csv("../Weather/Output/cities.csv")
data_df.head()

,City ID,City,Country,Date,Lat,Lng,Current Temp,Max Temp,Humidity (%),Cloudiness (%),Wind Speed (mph)
0,0,Bubaque,GW,1599440492,11.28,-15.83,79.52,79.52,83,100,18.48
1,1,Arcelia,MX,1599440493,18.28,-100.27,74.88,74.88,86,100,0.60
2,2,Wankyi,GH,1599440493,7.74,-2.10,69.84,69.84,97,100,4.88
3,3,Samarai,PG,1599440493,-10.62,150.67,78.80,78.80,86,97,17.09
4,4,Iranshahr,IR,1599440494,27.20,60.68,80.60,80.60,13,0,4.52

In [5]:
data_df.loc[:,'Humidity (%)'] = data_df['Humidity (%)'].astype("float")

In [6]:
  locations = data_df[["Lat", "Lng"]].astype(float)

In [7]:
# Configure gmaps with API key
gmaps.configure(api_key=g_key)

In [8]:
#Create a heat map that displays the humidity for every city from the part I of the homework.
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=data_df['Humidity (%)'], 
                               dissipating=False, max_intensity=100,
                                 point_radius = 1)
fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
#Narrow down the DataFrame to find your ideal weather condition. 
#Drop any rows that don't contain all three conditions. You want to be sure the weather is ideal.

ideal_places_data = data_df.loc[(data_df['Max Temp'] <= 80) &
                                                 (data_df['Humidity (%)'] < 55) &
                                                 (data_df['Cloudiness (%)'] < 30)]
ideal_places = ideal_places_data.reset_index(drop=True)


cities =ideal_places['City'].values.tolist()
ideal_places

,City ID,City,Country,Date,Lat,Lng,Current Temp,Max Temp,Humidity (%),Cloudiness (%),Wind Speed (mph)
0,17,Yangi Marg`ilon,UZ,1599440497,40.43,71.72,60.80,60.80,41.0,0,4.70
1,36,Marrakesh,MA,1599440503,31.63,-8.01,78.80,78.80,47.0,0,2.24
2,60,Airai,TL,1599440511,-8.93,125.41,72.12,72.12,43.0,11,6.33
3,98,KhƒÅsh,IR,1599440523,28.22,61.22,60.48,60.48,31.0,0,2.62
4,106,Dongsheng,CN,1599440527,39.82,109.98,67.10,67.10,45.0,0,9.33
5,122,Yumen,CN,1599440531,40.28,97.20,67.86,67.86,25.0,10,16.89
6,128,Swan Hill,AU,1599440533,-35.34,143.55,67.60,67.60,47.0,0,15.73
7,134,Miles City,US,1599440535,46.41,-105.84,71.60,71.60,37.0,1,20.80
8,144,Karratha,AU,1599440538,-20.74,116.85,75.27,75.27,52.0,0,12.06
9,148,Bay Roberts,CA,1599440539,47.60,-53.26,55.49,57.00,40.0,5,6.80
10,159,Port Hedland,AU,1599440544,-20.32,118.57,77.00,77.00,53.0,0,10.29
11,178,Krasnoarmeysk,RU,1599440550,51.02,45.70,61.00,61.00,30.0,1,1.99
12,188,Alta Floresta,BR,1599440553,-9.88,-56.09,79.32,79.32,26.0,0,1.95
13,236,Bom Sucesso,BR,1599440569,-21.03,-44.76,65.98,65.98,36.0,0,2.01
14,250,Tire,TR,1599440573,38.09,27.74,73.40,73.40,53.0,0,10.29
15,251,Navira√≠,BR,1599440574,-23.07,-54.19,76.42,76.42,42.0,5,3.65
16,252,Francisco S√°,BR,1599440574,-16.48,-43.49,75.20,75.20,44.0,0,2.24
17,280,Engenheiro Beltr√£o,BR,1599440582,-23.80,-52.27,70.74,70.74,48.0,0,3.06
18,284,Chokurdakh,RU,1599440584,70.63,147.92,50.25,50.25,49.0,9,9.48
19,300,Aksu,CN,1599440589,41.12,80.26,67.03,67.03,49.0,0,3.85
20,308,Haines Junction,CA,1599440575,60.75,-137.51,60.42,60.42,33.0,6,4.52
21,331,Rawson,AR,1599440600,-43.30,-65.10,51.98,51.98,54.0,0,8.66
22,359,Broken Hill,AU,1599440610,-31.95,141.43,69.80,69.80,26.0,0,16.11
23,361,Morros,BR,1599440610,-9.45,-46.30,72.50,72.50,26.0,0,4.61
24,363,Jiuquan,CN,1599440611,39.74,98.52,69.26,69.26,24.0,0,2.86
25,387,Upington,ZA,1599440618,-28.45,21.26,51.80,51.80,36.0,0,3.36
26,395,Port Augusta,AU,1599440620,-32.50,137.77,77.00,77.00,24.0,0,28.86
27,409,Birjand,IR,1599440625,32.87,59.22,60.80,60.80,26.0,0,4.70
28,411,KhalkhƒÅl,IR,1599440626,37.62,48.53,63.14,63.14,43.0,5,2.10
29,423,Colares,PT,1599440629,38.80,-9.45,72.99,75.99,49.0,0,7.00
30,450,Riach√£o das Neves,BR,1599440481,-11.75,-44.91,70.81,70.81,33.0,0,0.65
31,455,Seydi,TM,1599440640,39.48,62.91,57.42,57.42,35.0,0,14.41
32,485,Belle Fourche,US,1599440649,44.67,-103.85,73.45,75.00,31.0,1,6.93
33,495,Fairbanks,US,1599440382,64.84,-147.72,61.30,64.40,34.0,20,10.29
34,517,Bƒ´jƒÅr,IR,1599440660,35.87,47.61,56.82,56.82,36.0,0,2.73
35,543,Tsabong,BW,1599440668,-26.02,22.40,62.83,62.83,30.0,0,9.04

In [10]:
#Using Google Places API to find the first hotel for each city located within 5000 meters of your coordinates.
#Plot the hotels on top of the humidity heatmap with each pin containing the Hotel Name, City, and Country.
# Make a request for each of the indices
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
target_type = "lodging"
en = "en"
radius = 5000
name = []
address=[]
lati = []
long = []
City=[]
Country=[]

# Initialize count variables for record and set
item = 1
grupo = 1

for x in range(len(cities)):
    try:
        print(f"Processing Record {item} of Group {grupo} ... {cities[x]}")  
        params = {
                "location":str(ideal_places.loc[x,'Lat'])+"," + str(ideal_places.loc[x,'Lng']),
                "types": target_type,
                "radius": radius,
                "language":en,
                "key": g_key
                 }
        data = requests.get(base_url, params).json()
        #my_places= requests.get(f"{base_url}appid={weather_api_key}&units={unit_temp}&q={city}").json()
        City.append(cities[x])
        Country.append(ideal_places.loc[x,'Country'])
        name.append(data["results"][0]["name"])
        address.append(data["results"][0]["vicinity"])
        lati.append(data["results"][0]["geometry"]["location"]["lat"])
        long.append(data["results"][0]["geometry"]["location"]["lng"])    
        
        item += 1
        
        #If statement to limit API calls to 50
        if item > 50:
            grupo += 1
            item = 1
            time.sleep(1)
    
    except:
        print(f"There is no a hotel for '{cities[x]}' located within 5000 meters of your that city coordinates.")
        borrar=City.pop(-1)
        borrar2=Country.pop(-1)

print("Finish retrieving hotels data")

Processing Record 1 of Group 1 ... Yangi Marg`ilon
Processing Record 2 of Group 1 ... Marrakesh
Processing Record 3 of Group 1 ... Airai
Processing Record 4 of Group 1 ... KhƒÅsh
Processing Record 5 of Group 1 ... Dongsheng
Processing Record 6 of Group 1 ... Yumen
There is no a hotel for 'Yumen' located within 5000 meters of your that city coordinates.
Processing Record 6 of Group 1 ... Swan Hill
Processing Record 7 of Group 1 ... Miles City
Processing Record 8 of Group 1 ... Karratha
Processing Record 9 of Group 1 ... Bay Roberts
Processing Record 10 of Group 1 ... Port Hedland
Processing Record 11 of Group 1 ... Krasnoarmeysk
Processing Record 12 of Group 1 ... Alta Floresta
Processing Record 13 of Group 1 ... Bom Sucesso
Processing Record 14 of Group 1 ... Tire
Processing Record 15 of Group 1 ... Navira√≠
Processing Record 16 of Group 1 ... Francisco S√°
Processing Record 17 of Group 1 ... Engenheiro Beltr√£o
Processing Record 18 of Group 1 ... Chokurdakh
There is no a hotel for 'Chokurdakh' located within 5000 meters of your that city coordinates.
Processing Record 18 of Group 1 ... Aksu
Processing Record 19 of Group 1 ... Haines Junction
Processing Record 20 of Group 1 ... Rawson
Processing Record 21 of Group 1 ... Broken Hill
Processing Record 22 of Group 1 ... Morros
There is no a hotel for 'Morros' located within 5000 meters of your that city coordinates.
Processing Record 22 of Group 1 ... Jiuquan
Processing Record 23 of Group 1 ... Upington
Processing Record 24 of Group 1 ... Port Augusta
Processing Record 25 of Group 1 ... Birjand
Processing Record 26 of Group 1 ... KhalkhƒÅl
Processing Record 27 of Group 1 ... Colares
Processing Record 28 of Group 1 ... Riach√£o das Neves
Processing Record 29 of Group 1 ... Seydi
Processing Record 30 of Group 1 ... Belle Fourche
Processing Record 31 of Group 1 ... Fairbanks
Processing Record 32 of Group 1 ... Bƒ´jƒÅr
Processing Record 33 of Group 1 ... Tsabong
Finish retrieving hotels data

In [11]:
#Create Dataframe
my_hotels_df = pd.DataFrame({"Hotel": name,
                          "City": City,
                          "Country": Country,
                          "Address":address,
                          "Lat": lati,
                          "Lng": long,
                           })
my_hotels_df

,Hotel,City,Country,Address,Lat,Lng
0,Ikathouse,Yangi Marg`ilon,UZ,Margilan,40.461418,71.728314
1,Les Jardins de La Koutoubia,Marrakesh,MA,"26 Rue Koutoubia, Marrakech",31.626060,-7.991730
2,Juvinal Martin,Airai,TL,Atsabe,-8.930576,125.396797
3,ÿØŸÅÿ™ÿ± Ÿæ€åÿ¥ÿÆŸàÿßŸÜ ÿØŸàŸÑÿ™ ÿ¨ŸÖÿßŸÑ ÿ≤Ÿá€å (ÿÆÿßŸÑÿØ),KhƒÅsh,IR,Khash,28.217111,61.216804
4,Crowne Plaza Ordos,Dongsheng,CN,China,39.828710,109.961820
5,Lazy River Motor Inn,Swan Hill,AU,"188 Murray Valley Highway, Swan Hill",-35.323401,143.552596
6,FairBridge Inn & Suites Miles City,Miles City,US,"3111 Steel Street, Miles City",46.393891,-105.820613
7,ibis Styles Karratha,Karratha,AU,"35/45 Searipple Road, Karratha",-20.732225,116.846744
8,Stonewall Inn,Bay Roberts,CA,"227 Conception Bay Highway, Spaniard's Bay",47.610820,-53.283097
9,The Esplanade Hotel,Port Hedland,AU,"2 Anderson Street, Port Hedland",-20.313925,118.576081
10,Gostinitsa Komfort,Krasnoarmeysk,RU,"Ulitsa Ul'yanovskaya, 60–∞, Krasnoarmeysk",51.016379,45.698318
11,Floresta Amazonica Hotel,Alta Floresta,BR,"Avenida Perimetral, Avenida Ns Oeste, 2001, Al...",-9.878056,-56.097778
12,Hotel Bela Vista,Bom Sucesso,BR,"Pra√ßa Padroeira, 100 - Centro, Bom Sucesso",-21.032590,-44.755762
13,G√ºlc√ºoƒülu Konaklarƒ±,Tire,TR,"Kurtulu≈ü, T√ºrkocaƒüƒ± Caddesi No:56",38.084422,27.737733
14,Dubai Hotel - Tamb√©m sua casa!,Navira√≠,BR,"Rua Riachuelo, 450 - Jardim Vale Encantado, Na...",-23.065598,-54.197459
15,Amaralina Hotel,Francisco S√°,BR,"Pra√ßa Jacinto Silveira, 11 - Centro, Francisco S√°",-16.475015,-43.491123
16,Hotel Vit√≥ria-R√©gia,Engenheiro Beltr√£o,BR,"Avenida Sete de Setembro, 579 - Centro, Engenh...",-23.798806,-52.259946
17,Pudong Holiday Hotel,Aksu,CN,"‰∫§ÈÄöË•øË∑Ø1Âè∑, Jiaotong Road, Aksu City, Aksu Prefecture",41.141760,80.291396
18,Parkside Inn,Haines Junction,CA,"137 Haines Highway, Haines Junction",60.750961,-137.509796
19,Hotel Punta Le√≥n,Rawson,AR,"Juan de la Piedra 210, Playa Union",-43.320090,-65.048961
20,Daydream Motel & Cottages,Broken Hill,AU,"77 Argent Street, Broken Hill",-31.962251,141.459816
21,Jiuquan Hotel,Jiuquan,CN,"33 Jiefang Road, Suzhou District, Jiuquan",39.737397,98.507802
22,River Place Manor,Upington,ZA,"36 a Steenbok Avenue, Middelpos, Upington",-28.449554,21.263565
23,Majestic Oasis Apartments,Port Augusta,AU,"Marryatt Street, Port Augusta",-32.488861,137.763138
24,Birjand Tourist Hotel,Birjand,IR,Birjand,32.871375,59.230780
25,Khalkhal Tourist Hotel,KhalkhƒÅl,IR,"Khalkhal, Molavi",37.607196,48.542808
26,Arribas Sintra Hotel,Colares,PT,"Avenida Alfredo Coelho 28, Colares",38.817251,-9.475624
27,Casa de v√≥ Dina,Riach√£o das Neves,BR,"Rua Pantale√£o √Åguiar, 214, Riach√£o das Neves",-11.748987,-44.910353
28,√áagalar D√ºn√Ω√§si,Seydi,TM,"√áagalar D√ºn√Ω√§si, Se√Ωdi",39.474692,62.918334
29,Kings Inn,Belle Fourche,US,"518 National Street, Belle Fourche",44.662095,-103.852239
30,Westmark Fairbanks Hotel & Conference Center,Fairbanks,US,"813 Noble Street, Fairbanks",64.839906,-147.712346
31,ŸÖÿ≥ÿßŸÅÿ±ÿÆÿßŸÜŸá ⁄ØŸÑÿ¥ŸÜ,Bƒ´jƒÅr,IR,ÿ®Ÿäÿ¨ÿßÿ±ÿå,35.869192,47.606488
32,Springbok Motel,Tsabong,BW,Tshabong,-26.017254,22.403855

In [12]:
my_hotels_df['Pin info']= my_hotels_df["Hotel"]+", "+my_hotels_df["City"]+", "+my_hotels_df["Country"]
my_hotels_df['Pin info']

0                        Ikathouse, Yangi Marg`ilon, UZ
1            Les Jardins de La Koutoubia, Marrakesh, MA
2                             Juvinal Martin, Airai, TL
3          ÿØŸÅÿ™ÿ± Ÿæ€åÿ¥ÿÆŸàÿßŸÜ ÿØŸàŸÑÿ™ ÿ¨ŸÖÿßŸÑ ÿ≤Ÿá€å (ÿÆÿßŸÑÿØ), KhƒÅsh, IR
4                     Crowne Plaza Ordos, Dongsheng, CN
5                   Lazy River Motor Inn, Swan Hill, AU
6     FairBridge Inn & Suites Miles City, Miles City...
7                    ibis Styles Karratha, Karratha, AU
8                        Stonewall Inn, Bay Roberts, CA
9                 The Esplanade Hotel, Port Hedland, AU
10                Gostinitsa Komfort, Krasnoarmeysk, RU
11          Floresta Amazonica Hotel, Alta Floresta, BR
12                    Hotel Bela Vista, Bom Sucesso, BR
13                        G√ºlc√ºoƒülu Konaklarƒ±, Tire, TR
14          Dubai Hotel - Tamb√©m sua casa!, Navira√≠, BR
15                    Amaralina Hotel, Francisco S√°, BR
16          Hotel Vit√≥ria-R√©gia, Engenheiro Beltr√£o, BR
17                       Pudong Holiday Hotel, Aksu, CN
18                    Parkside Inn, Haines Junction, CA
19                         Hotel Punta Le√≥n, Rawson, AR
20           Daydream Motel & Cottages, Broken Hill, AU
21                           Jiuquan Hotel, Jiuquan, CN
22                      River Place Manor, Upington, ZA
23          Majestic Oasis Apartments, Port Augusta, AU
24                   Birjand Tourist Hotel, Birjand, IR
25                 Khalkhal Tourist Hotel, KhalkhƒÅl, IR
26                    Arribas Sintra Hotel, Colares, PT
27               Casa de v√≥ Dina, Riach√£o das Neves, BR
28                           √áagalar D√ºn√Ω√§si, Seydi, TM
29                         Kings Inn, Belle Fourche, US
30    Westmark Fairbanks Hotel & Conference Center, ...
31                            ŸÖÿ≥ÿßŸÅÿ±ÿÆÿßŸÜŸá ⁄ØŸÑÿ¥ŸÜ, Bƒ´jƒÅr, IR
32                         Springbok Motel, Tsabong, BW
Name: Pin info, dtype: object

In [13]:
# Create bank symbol layer

hotel_name = my_hotels_df['Pin info'].tolist()
locations = my_hotels_df[["Lat", "Lng"]].astype(float)
hotel_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
    info_box_content=[f"Hotel: {hotel}" for hotel in hotel_name]
)

fig = gmaps.figure()
fig.add_layer(hotel_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# Create a combined map
fig = gmaps.figure()

fig.add_layer(heat_layer)
fig.add_layer(hotel_layer)

fig

Figure(layout=FigureLayout(height='420px'))